create table users (
    id bigint generated by default as identity,
    name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    constraint pk_users primary key (id),
    constraint uk_users_email unique (email)
);

create table products (
    id bigint generated by default as identity,
    name varchar(255) not null,
    description varchar(1000) not null,
    price numeric(10, 2) not null,
    image_url varchar(255) not null,
    florist_id bigint,
    florist_name varchar(255) not null,
    florist_logo_url varchar(255),
    in_stock boolean not null,
    constraint pk_products primary key (id)
);

create table product_mood_tags (
    product_id bigint not null,
    mood_tag varchar(255) not null,
    constraint fk_product_mood_tags_product
        foreign key (product_id) references products (id)
);

create table cart_items (
    id bigint generated by default as identity,
    user_id bigint not null,
    product_id bigint not null,
    quantity integer not null,
    constraint pk_cart_items primary key (id),
    constraint uk_cart_items_user_product unique (user_id, product_id),
    constraint fk_cart_items_user
        foreign key (user_id) references users (id),
    constraint fk_cart_items_product
        foreign key (product_id) references products (id)
);

create table florists (
    id bigint generated by default as identity,
    user_id bigint not null,
    store_name varchar(255),
    bio text,
    logo_url varchar(255),
    street varchar(255),
    city varchar(255),
    zip_code varchar(255),
    max_daily_capacity integer,
    delivery_coverage varchar(255),
    time_slots varchar(255),
    prep_lead_time_hours integer,
    onboarding_complete boolean not null,
    constraint pk_florists primary key (id),
    constraint uk_florists_user unique (user_id),
    constraint fk_florists_user
        foreign key (user_id) references users (id)
);

create table orders (
    id bigint generated by default as identity,
    user_id bigint not null,
    recipient_name varchar(255) default 'COD' not null,
    recipient_address varchar(1000) not null,
    card_message varchar(200),
    delivery_date date not null,
    time_slot varchar(255) not null,
    payment_method varchar(255) not null,
    status varchar(255) not null,
    courier_name varchar(255),
    tracking_number varchar(255),
    estimated_delivery_date date,
    latest_shipping_status varchar(255),
    fulfillment_image_url varchar(255),
    proof_image_url varchar(255),
    total_amount numeric(10, 2) not null,
    constraint pk_orders primary key (id),
    constraint fk_orders_user
        foreign key (user_id) references users (id)
);

create table order_items (
    id bigint generated by default as identity,
    order_id bigint not null,
    product_id bigint not null,
    product_name varchar(255) not null,
    unit_price numeric(10, 2) not null,
    quantity integer not null,
    constraint pk_order_items primary key (id),
    constraint fk_order_items_order
        foreign key (order_id) references orders (id),
    constraint fk_order_items_product
        foreign key (product_id) references products (id)
);

create table tracking_events (
    id bigint generated by default as identity,
    order_id bigint not null,
    status varchar(255) not null,
    description varchar(500) not null,
    timestamp timestamp(6) not null,
    constraint pk_tracking_events primary key (id),
    constraint fk_tracking_events_order
        foreign key (order_id) references orders (id)
);

create table delivery_addresses (
    id bigint generated by default as identity,
    user_id bigint not null,
    label varchar(255) not null,
    recipient_name varchar(255) not null,
    phone_number varchar(255),
    address_line varchar(500) not null,
    default_address boolean not null,
    constraint pk_delivery_addresses primary key (id),
    constraint fk_delivery_addresses_user
        foreign key (user_id) references users (id)
);

create table saved_dates (
    id bigint generated by default as identity,
    user_id bigint not null,
    label varchar(100) not null,
    event_date date not null,
    is_recurring boolean not null,
    notified_year integer,
    constraint pk_saved_dates primary key (id),
    constraint fk_saved_dates_user
        foreign key (user_id) references users (id)
);
