create table buyer_notifications (
    id bigint generated by default as identity,
    user_id bigint not null,
    saved_date_id bigint not null,
    type varchar(100) not null,
    title varchar(255) not null,
    message varchar(1000) not null,
    event_date date not null,
    notification_year integer not null,
    read_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    constraint pk_buyer_notifications primary key (id),
    constraint uk_buyer_notifications_saved_date_year unique (user_id, saved_date_id, type, notification_year),
    constraint fk_buyer_notifications_user
        foreign key (user_id) references users (id),
    constraint fk_buyer_notifications_saved_date
        foreign key (saved_date_id) references saved_dates (id)
);
