create table reviews (
    id bigint generated by default as identity,
    user_id bigint not null,
    order_id bigint not null,
    product_id bigint not null,
    florist_id bigint not null,
    product_rating integer not null check (product_rating >= 1 and product_rating <= 5),
    florist_rating integer not null check (florist_rating >= 1 and florist_rating <= 5),
    comment text,
    created_at timestamp(6) not null default current_timestamp,
    constraint pk_reviews primary key (id),
    constraint uk_reviews_user_order_product unique (user_id, order_id, product_id),
    constraint fk_reviews_user foreign key (user_id) references users (id),
    constraint fk_reviews_order foreign key (order_id) references orders (id),
    constraint fk_reviews_product foreign key (product_id) references products (id),
    constraint fk_reviews_florist foreign key (florist_id) references florists (id)
);
