create table conversations (
    id bigint generated by default as identity,
    buyer_id bigint not null,
    florist_id bigint not null,
    order_id bigint not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint pk_conversations primary key (id),
    constraint uk_conversations_order unique (order_id),
    constraint fk_conversations_buyer foreign key (buyer_id) references users (id),
    constraint fk_conversations_florist foreign key (florist_id) references florists (id),
    constraint fk_conversations_order foreign key (order_id) references orders (id)
);

create table messages (
    id bigint generated by default as identity,
    conversation_id bigint not null,
    sender_type varchar(255) not null,
    content text not null,
    created_at timestamp(6) not null,
    constraint pk_messages primary key (id),
    constraint fk_messages_conversation foreign key (conversation_id) references conversations (id)
);
